[package]
name = "rd-preprocess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = "0.4.1"
regex = "1.9.5"
serde_json = "1.0.107"
zip = "0.6.6"
